[package]
name = "dogfight-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
dogfight-shared = { path = "../shared" }
glam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rand = { workspace = true }
rand_pcg = { workspace = true }
